docs: add push error handling

diff --git a/.github/workflows/check_publications.yml b/.github/workflows/check_publications.yml
--- a/.github/workflows/check_publications.yml
+++ b/.github/workflows/check_publications.yml
@@ -33,5 +33,5 @@ jobs:
             echo "No changes in publication backups."
           else
             git commit -m "docs: auto-update publications backup status table [skip ci]"
-            git push
+            git push || echo "Push failed, but continuing"
           fi
